#!/bin/bash

# Update the system
sudo apt update
sudo apt upgrade

# Add ROS repository and set up keys
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654

# Update the package list once more
sudo apt update

# Install ROS
sudo apt install ros-melodic-desktop-full

# Set up environment
echo "source /opt/ros/melodic/setup.bash" >> ~/.bashrc
source ~/.bashrc

# Install tools and dependencies
sudo apt install python-rosdep python-rosinstall python-rosinstall-generator python-wstool build-essential

# Initialize rosdep
sudo apt install python-rosdep
sudo rosdep init
rosdep update
